# Generated by Django 4.2.11 on 2025-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
