# Generated by Django 4.2.11 on 2025-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_verification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
