# Generated by Django 4.2.11 on 2025-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileoptimization',
            old_name='experience',
            new_name='general_advice',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='comparator',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='improved_headline',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='improved_summary',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='summary',
        ),
        migrations.AddField(
            model_name='profileoptimization',
            name='section_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileoptimization',
            name='sections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
