# Generated by Django 4.2.11 on 2025-11-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_optimizer', '0002_rename_experience_profileoptimization_general_advice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_status', models.CharField(default='pending', max_length=16)),
                ('ocr_raw_json', models.JSONField(blank=True, null=True)),
                ('ocr_full_text', models.TextField(blank=True)),
                ('ocr_error_message', models.TextField(blank=True)),
                ('cleaned_profile_json', models.JSONField(blank=True, null=True)),
                ('gpt_raw_json', models.JSONField(blank=True, null=True)),
                ('gpt_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileOptimization',
        ),
    ]
