# Generated by Django 4.2.11 on 2025-12-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_optimizer', '0003_profileanalysis_delete_profileoptimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileanalysis',
            name='about_outline',
            field=models.JSONField(default=list, help_text='Outline array, usually ["Hook","Credibility","Proof","CTA"].'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='asset_specs',
            field=models.JSONField(default=list, help_text='List of asset spec objects, e.g. [{"name":"Banner","size":"1584×396"},...].'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='cta_snippets',
            field=models.JSONField(default=list, help_text='List of CTA snippet strings.'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='headline_options',
            field=models.JSONField(default=list, help_text='List of generated headline options.'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='notes',
            field=models.TextField(default='No PII stored or extracted.', help_text='Analyzer notes; must respect PII rules.'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='overall_score',
            field=models.IntegerField(default=0, help_text='0–100 overall score from analyzer.'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='profile_url',
            field=models.URLField(blank=True, help_text='Optional: user-supplied LinkedIn profile URL.', null=True),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='quick_wins',
            field=models.JSONField(default=list, help_text='List of quick wins (strings).'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='raw_model_meta',
            field=models.JSONField(default=dict, help_text='Raw meta from LLM calls (tokens, cost, model, prompts, etc.).'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='rubric_json',
            field=models.JSONField(default=dict, help_text='Rubric scores JSON: photo/banner/headline/about/services/featured/experience/skills/cta_consistency.'),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='screenshot_url',
            field=models.URLField(blank=True, help_text='Optional: S3/GCS path if screenshot is stored separately.', null=True),
        ),
        migrations.AddField(
            model_name='profileanalysis',
            name='section',
            field=models.CharField(default='full', help_text='Section focus: "full"|"headline"|"about"|"services"|"featured"|"experience"|"skills".', max_length=32),
        ),
        migrations.AlterField(
            model_name='profileanalysis',
            name='cleaned_profile_json',
            field=models.JSONField(blank=True, help_text='Heuristically cleaned profile JSON derived from OCR.', null=True),
        ),
        migrations.AlterField(
            model_name='profileanalysis',
            name='gpt_raw_json',
            field=models.JSONField(blank=True, help_text='Legacy GPT output JSON (pre-LeadzMachine schema).', null=True),
        ),
        migrations.AlterField(
            model_name='profileanalysis',
            name='gpt_score',
            field=models.IntegerField(blank=True, help_text='Legacy single score field.', null=True),
        ),
        migrations.AlterField(
            model_name='profileanalysis',
            name='ocr_error_message',
            field=models.TextField(blank=True, help_text='Any OCR / parser errors.'),
        ),
        migrations.AlterField(
            model_name='profileanalysis',
            name='ocr_full_text',
            field=models.TextField(blank=True, help_text='Full text extracted from OCR.'),
        ),
        migrations.AlterField(
            model_name='profileanalysis',
            name='ocr_raw_json',
            field=models.JSONField(blank=True, help_text='Raw JSON response from Google Vision / Gemini OCR.', null=True),
        ),
    ]
