# Generated by Django 4.2.11 on 2025-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_optimizer', '0004_profileanalysis_about_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileanalysis',
            name='store_image',
            field=models.BooleanField(default=True, help_text='Whether this screenshot should be stored long-term.'),
        ),
    ]
