# Generated by Django 4.2.11 on 2025-11-25 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(blank=True, max_length=256)),
                ('summary', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comparator', models.CharField(blank=True, max_length=128, null=True)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('improved_headline', models.CharField(blank=True, max_length=256, null=True)),
                ('improved_summary', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
