# Generated by Django 4.2.11 on 2025-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileOptimization',
        ),
    ]
