# Generated by Django 4.2.11 on 2025-12-13 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_url', models.URLField(blank=True, help_text='Optional: LinkedIn post URL where this comment will be used.', null=True)),
                ('post_text', models.TextField(blank=True, help_text='Post content or snippet captured from the LinkedIn DOM.')),
                ('tone', models.CharField(blank=True, help_text='Tone hint, e.g. "positive", "insightful", "celebration".', max_length=64)),
                ('audience', models.CharField(blank=True, help_text='Optional: target audience / ICP for the comment.', max_length=128)),
                ('language', models.CharField(blank=True, help_text='Optional: language code or name, e.g. en, hi, fr.', max_length=32)),
                ('extra_context', models.JSONField(blank=True, help_text='Optional JSON with additional knobs (length, style flags, etc.).', null=True)),
                ('primary_comment', models.TextField(blank=True, help_text='Main suggested comment text (shown in the draft textarea).')),
                ('alt_comments', models.JSONField(default=list, help_text='List of alternative comment suggestions (strings).')),
                ('style_tags', models.JSONField(default=list, help_text="Tags summarizing style, e.g. ['supportive', 'concise'].")),
                ('raw_model_meta', models.JSONField(default=dict, help_text='Raw meta from LLM calls (model, tokens, raw_output, etc.).')),
                ('status', models.CharField(default='ok', help_text='Generation status: "ok" or "failed".', max_length=16)),
                ('error_message', models.TextField(blank=True, help_text='If failed, store error details for debugging.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
