# Generated by Django 4.2.11 on 2025-12-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentgeneration',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional screenshot used for OCR / comment generation.', null=True, upload_to='comment_screenshots/'),
        ),
    ]
