# Generated by Django 4.2.11 on 2025-12-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_generator', '0002_commentgeneration_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentgeneration',
            name='screenshot',
        ),
    ]
