# Generated by Django 4.2.11 on 2025-11-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='added_by',
        ),
    ]
