# Generated by Django 4.2.11 on 2025-11-19 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_remove_lead_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
