# Generated by Django 4.2.11 on 2025-11-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.CharField(blank=True, default='Prospect', max_length=255, null=True),
        ),
    ]
